version: "3.9"

services:
  app:
    build: .
    container_name: nest-app
    ports:
      - "3000:3000"
    environment:
      HOSTDB: db
      PORTDB: 5432
      USERNAMEDB: nestuser
      PASSWORDDB: nestpass
      DATABASENAME: nestdb
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpass
      POSTGRES_DB: nestdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: